permalink: /blog/:title.html
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile"]
auto: false
pygments: true
title : nateirwin.net
production_url : http://nateirwin.github.com
markdown: kramdown
# baseurl: http://nateirwin.net